baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://oflannabhra.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html
 
# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page
 
# Format titles with titlecase?
titlecase: true
 
# Change default template file (in _templates/)
post_template: post.html
page_template: page
draft_template: draft

gems: [octopress-genesis-theme, octopress-gist, octopress-codefence, octopress-markdown-tag]