# Site settings
title: O'Flannabhra
email: oflannabhra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code, thoughts, mostly code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.oflannabhra.com" # the base hostname & protocol for your site
twitter_username: oflannabhra
github_username:  oflannabhra

# Build settings
markdown: kramdown
